### ISSUE TITLE
**Team A3, the HKS students: Prioritize setting up a solid website shell to get the project flow going**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#10]
As a project team, we want to set up our website shell early on and establish best practices in commenting our code, so that we can get the project flow going and have a place to put content and analysis in an organic way.

**Definition of Done:**

- [X] push html, css and js shell to group repository as first step
- [X] comment code so that teamwork within the code becomes smoother

**Tasks involved:**
- [X] Set up html, css and javascript shell
- [X] Save it to our shared repository
- [X] Include comment lines in the code, so all team members know what's going on
