### ISSUE TITLE
**Team A3: Develop D3 skills for effective visualisation**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#11]
**As a** graduate students at HKS,

**We want** to learn how to visualize data using D3,

**So that** we can provide easily digestible, yet effective, visual information in our second year thesis. 

**Definition of Done:**
- [x] include1-2 D3 graphics on our website

**Tasks involved:**
- [x] align as a group on which graphics to include
- [x] Learn about D3
- [x] produce the graphic
