### ISSUE TITLE
**Team A3, the HKS students: provide inital content and think through website design**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#13]
As a team building a website that should be valuable to someone, we first need to research valuable content & decide on how to present it, in order to have something worthwhile to fill the website with. 

**Definition of Done:**
- [x] Have enough content ready to populate a first version of the website
- [x] For mvp: analysis can be screenshotted rather than in D3 etc.

**Tasks involved:**
- [x] Finalise data sources for global 
- [x] Do 2-3 pieces of interesting data analysis on correlations between COVID incidence, death rate, air pollution and socioeconomic markers
- [x] Talk with team about structure of website. Preliminary idea:
- go from global to local and finish with some caveats on the research that's out there / why causation is difficult to assess. 
- [x] Document sources well
