### ISSUE TITLE
**John Doe, generic website visitor: Easy to navigate page**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#57]
**As a** generic website visitor 

**I want** pages I visit to be clean and easy to navigate 

**so it** doesn't hurt my eyes and I don't get angry trying to find lost pages. 

**Definition of Done:**

- [x] Clean, easy to read style
- [x] The navigation system is intuitive on every page

**Tasks:** 
- [x] Fix broken topnav links
- [x] Increase margins on the side to make page more readible on small divices.
- [x] Make objects float where possible/sensible
- [x] fix typos and formatting glitch of lit review table

**Comment by sshaffer-hks** [comment]
Starting on fixing topnav links
