### ISSUE TITLE
**Janina: Accessible & easy to understand information**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#8]
**As a** member of the general public, I don’t have the time to keep up to date with academic literature, but I read in the news about a connection between underlying conditions and COVID cases. I am concerned with my environment & health issues. 

**I want** a place with easily digestible information on this topic, 

**so that** I can inform myself quickly but accurately. 

**Definition of done:**
- [x] No one is held back by jargon (run it by JS mom and see if she likes it)
- [x] Key points are summarised and easily visible

**Tasks involved:**
- [x] make glossary or explain jargon in text FLAG: dependent on other tasks (8 points) Super cool would be glossary as you hover over a point
- [x] Have key insights visible
- [x]  5 glossary per (intro and data) page

**Comment by schijoh** [comment]
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/media-resources/science-in-5/episode-9---air-pollution-covid-19

We could embed this video on the non-expert version of the website?
