### ISSUE TITLE
**Ndubuisi: Credible & referenceable information**

### ISSUE THREAD

**Issue by schijoh** [code4policy/Team-A3#9]
**As an** activist advocating on environmental justice topics, 

**I am looking for** well sourced, referenceable and ideally downloadable information, 

**so that** I can credibly share and use this information. 

**Definition of Done:**
- [x] A downloadable, printable fact-sheet

**Tasks involved:**
- [x] Delete links from factsheet - make sure it's printable (i.e. make bitly's)
- [x] Hyperlink more important datasources; source graphs properly
- [x] Position prominently, but not in your face. Include ounce of information about it.
